services:
  mirror:
    image: rearview-action-manager/rearview-mirror:latest
    build:
      context: ./rearview-action-manager-mirror
      target: mirror-dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./rearview-action-manager-mirror/src
          action: sync
          target: /app/src
        - path: ./rearview-action-manager-mirror/App.jsx
          action: sync
          target: /app/src/App.jsx
        - path: ./rearview-action-manager-mirror/package.json
          action: rebuild
#    networks:
#      - front-tier
#      - back-tier
#    configs:
#      - httpd-config
#    secrets:
#      - server-certificate

  cam:
    image: rearview-action-manager/rearview-cam:latest
    build:
      context: ./rearview-action-manager-cam
      target: cam-base
    ports:
      - "8080:8080"
    depends_on:
      storage:
        condition: service_healthy
    develop:
      watch:
        - path: ./rearview-action-manager-cam
          action: sync
          target: ./rearview-action-manager-cam
        - path: ./rearview-action-manager-can/go.mod
          action: rebuild
#    volumes:
#      - db-data:/etc/data
#    networks:
#      - back-tier

  storage:
    image: postgres:17-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: publicPass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

#    networks:
#      - back-tier

volumes:
  pgdata:
    driver: local

#
#configs:
#  httpd-config:
#    external: true
#
#secrets:
#  server-certificate:
#    external: true
#
#networks:
#  # The presence of these objects is sufficient to define them
#  front-tier: {}
#  back-tier: {}
